import { defineRouteMiddleware } from "@astrojs/starlight/route-data";

// Docs navigation lives in the top bar for everything except the component reference:
// /components/* pages get the left sidebar back (the autogenerated component list in
// astro.config.mjs's `sidebar`) so readers can hop between the 60+ components without
// returning to the gallery. `hasSidebar` drives both PageFrame.astro's sidebar slot and
// Starlight's own `data-has-sidebar` layout attribute, so flipping it here keeps every
// downstream consumer (header padding, content inset, mobile menu) in sync.
export const onRequest = defineRouteMiddleware((context) => {
  const { starlightRoute } = context.locals;
  starlightRoute.hasSidebar = starlightRoute.id.startsWith("components/");
});
